---
- name: Fetch Running EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - /home/durga/ansible_learnings/group_vars/all/aws_credentials.yml  # Update with your correct path

  vars:
    regions:
      - us-east-1
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-central-1
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ap-northeast-2
      - sa-east-1

  tasks:
    - name: Get EC2 instances in each region
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
      register: ec2_info
      loop: "{{ regions }}"
      loop_control:
        loop_var: region

    - name: Filter running instances
      set_fact:
        running_instances: "{{ running_instances | default([]) + [{'region': item.region, 'instances': item.instances | selectattr('state.name', 'equalto', 'running') | map(attribute='instance_id') | list}] }}"
      loop: "{{ ec2_info.results }}"
      loop_control:
        loop_var: item
      when: item.instances is defined

    - name: Print running instances
      debug:
        msg: "Region: {{ item.region }}, Running Instance IDs: {{ item.instances }}"
      loop: "{{ running_instances }}"
      loop_control:
        loop_var: item
      when: item.instances | length > 0
