---
- name: Printing my name
  hosts: localhost
  connection: local

  vars_files:
    - my_vars.yaml

  tasks:
    - name: Printing name task
      ansible.builtin.debug:
        msg: "Hi {{ my_string }} "
    - name: Load vars
      ansible.builtin.include_vars:
        file: more_vars.yaml      
    - name: Printing other variables
      vars:
          var1: FirstVar
          var2: SecondVar
      ansible.builtin.debug:
        msg: "Task level variables are {{ var1}} , {{ var1 }}, {{ var3 }} from more"
    
